services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    networks:
      - hypertube
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "example", "-u", "user"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432

  server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - hypertube
    volumes:
      - .:/app

networks:
  hypertube:
    driver: bridge

