name: Test
on: push

jobs:
  migrate:
    runs-on: ubuntu-latest
    container: golang:1.25.0-bookworm
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: example
        ports:
          - 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Install GORM
        run: |
          go get -u gorm.io/gorm
          go get -u gorm.io/driver/postgres
